### ISSUE TITLE
Rename "updateMe-Scrapping" to "updateMe-Scraping"

### ISSUE THREAD

**Issue by Felitendo** [anfreire/updateMe-Scraping#11]
Hey,
thanks for the great work so far. Would you mind updating the Repository Name to "updateMe-Scraping", because Scrapping means dumping/removing and I think you wanted to name it Scraping like in Web Scraping. GitHub will also redirect every request from https://github.com/anfreire/updateMe-Scrapping to https://github.com/anfreire/updateMe-Scraping by default as long as no other Repository called "updateMe-Scrapping" is created by you.

**Comment by Felitendo** [comment]
I saw you've changed it. Thanks <3

**Comment by anfreire** [comment]
Yes, I saw your suggestion and changed the repository name as you recommended. Thank you for catching that typo.

I apologize for not responding sooner. I've had a lot on my plate lately and have been quite busy.
