### ISSUE TITLE
Add "Revanced Extended Beta" Provider

### ISSUE THREAD

**Issue by Felitendo** [anfreire/updateMe-Scraping#14]
Hey it's me again.
On the Revanced Extended GitHub Page are beta versions for example YouTube and YT Music and it would be cool if this Provider could be added to fetch all the beta releases :)

**Comment by anfreire** [comment]
I've added all the missing xManager Spotify flavors:

- Cloned
- Amoled Cloned
- Experimental
- Amoled Experimental
- Experimental Cloned
- Amoled Experimental Cloned

These were added because the Spotify mod is currently not working. Let's hope they fix it soon.

I'm closing this issue now.
